java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/abcd/asa:latest'
  ingressHost: abcd-asa-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: abcd
  environment:
